[tox]
envlist = py310,py311,py312,py313
isolated_build = true

[testenv]
deps =
    .[dev]
    sentinos-sdk-core>=0.1.1
commands =
    python -m ruff check sentinos tests
    python -m mypy sentinos
    python -m pytest -q
